### Nominal/OHE Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
## Create a simple dataframe
df = pd.DataFrame({
    'color' : ['red','blue','green','red','blue','green']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [4]:
## Create a instance of OneHotEncoder
encoder=OneHotEncoder()

In [5]:
## Perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [6]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [7]:
encoder.transform([['blue']]).toarray()

/Users/chetanjanmejay/Desktop/Python/venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [7]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0
5         0.0          1.0        0.0

In [14]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0
5  green         0.0          1.0        0.0

In [ ]:
## Label Encoder.
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [ ]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [18]:
Label_df=lbl_encoder.fit_transform(df[['color']])

/Users/chetanjanmejay/Desktop/Python/venv/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [15]:
lbl_encoder.transform([['red']])

/Users/chetanjanmejay/Desktop/Python/venv/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [16]:
lbl_encoder.transform([['green']])

/Users/chetanjanmejay/Desktop/Python/venv/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [17]:
lbl_encoder.transform([['blue']])

/Users/chetanjanmejay/Desktop/Python/venv/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [20]:
Label_df

array([2, 0, 1, 2, 0, 1])

In [23]:
## Ordinal Encoding

from sklearn.preprocessing import OrdinalEncoder

In [24]:
# create a sample dataframe with an ordinal variable
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [25]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [29]:
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [30]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [31]:
encoder.transform([['small']])

/Users/chetanjanmejay/Desktop/Python/venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

In [32]:
encoder.transform([['medium']])

/Users/chetanjanmejay/Desktop/Python/venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])

In [33]:
encoder.transform([['large']])

/Users/chetanjanmejay/Desktop/Python/venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[2.]])