### Data Manipulation and Analysis with Pandas.
Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, mmaking it easier to clean , transform, and extract insights from data. In this lesson, we will cover various data manioulation and analysis techniques using Pandas.

In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('sample_missing_values.csv')
df.head(5)

   ID     Name   Age   Salary Department
0   1    Alice  25.0  50000.0         HR
1   2      Bob   NaN  60000.0    Finance
2   3  Charlie  30.0      NaN        NaN
3   4      NaN  22.0  45000.0         IT
4   5      Eve   NaN  52000.0         HR

In [5]:
df.tail(5)

   ID    Name   Age   Salary Department
5   6   Frank  29.0      NaN    Finance
6   7     NaN  35.0  58000.0         IT
7   8  Hannah   NaN  61000.0        NaN
8   9     Ian  40.0      NaN    Finance
9  10    Jack  28.0  49000.0         HR

In [6]:
df.describe()

             ID        Age        Salary
count  10.00000   7.000000      7.000000
mean    5.50000  29.857143  53571.428571
std     3.02765   6.039552   6133.436852
min     1.00000  22.000000  45000.000000
25%     3.25000  26.500000  49500.000000
50%     5.50000  29.000000  52000.000000
75%     7.75000  32.500000  59000.000000
max    10.00000  40.000000  61000.000000

In [7]:
df.dtypes

ID              int64
Name           object
Age           float64
Salary        float64
Department     object
dtype: object

In [8]:
## Handling missing values.
df.isnull()

      ID   Name    Age  Salary  Department
0  False  False  False   False       False
1  False  False   True   False       False
2  False  False  False    True        True
3  False   True  False   False       False
4  False  False   True   False       False
5  False  False  False    True       False
6  False   True  False   False       False
7  False  False   True   False        True
8  False  False  False    True       False
9  False  False  False   False       False

In [9]:
df.isnull().any()

ID            False
Name           True
Age            True
Salary         True
Department     True
dtype: bool

In [10]:
df.isnull().sum()

ID            0
Name          2
Age           3
Salary        3
Department    2
dtype: int64

In [11]:
df_filled=df.fillna(0)

In [12]:
## filling missing values with mean of column.
df['Salary_fillNA']=df['Salary'].fillna(df['Salary'].mean())
df

   ID     Name   Age   Salary Department  Salary_fillNA
0   1    Alice  25.0  50000.0         HR   50000.000000
1   2      Bob   NaN  60000.0    Finance   60000.000000
2   3  Charlie  30.0      NaN        NaN   53571.428571
3   4      NaN  22.0  45000.0         IT   45000.000000
4   5      Eve   NaN  52000.0         HR   52000.000000
5   6    Frank  29.0      NaN    Finance   53571.428571
6   7      NaN  35.0  58000.0         IT   58000.000000
7   8   Hannah   NaN  61000.0        NaN   61000.000000
8   9      Ian  40.0      NaN    Finance   53571.428571
9  10     Jack  28.0  49000.0         HR   49000.000000

In [13]:
df.dtypes

ID                 int64
Name              object
Age              float64
Salary           float64
Department        object
Salary_fillNA    float64
dtype: object

In [14]:
## rename the columns
df=df.rename(columns={'ID':'College Id'})
df

   College Id     Name   Age   Salary Department  Salary_fillNA
0           1    Alice  25.0  50000.0         HR   50000.000000
1           2      Bob   NaN  60000.0    Finance   60000.000000
2           3  Charlie  30.0      NaN        NaN   53571.428571
3           4      NaN  22.0  45000.0         IT   45000.000000
4           5      Eve   NaN  52000.0         HR   52000.000000
5           6    Frank  29.0      NaN    Finance   53571.428571
6           7      NaN  35.0  58000.0         IT   58000.000000
7           8   Hannah   NaN  61000.0        NaN   61000.000000
8           9      Ian  40.0      NaN    Finance   53571.428571
9          10     Jack  28.0  49000.0         HR   49000.000000

In [15]:
## change datatype
df['Age_new']=df['Age'].fillna(df['Age'].mean()).astype(int)
df

   College Id     Name   Age   Salary Department  Salary_fillNA  Age_new
0           1    Alice  25.0  50000.0         HR   50000.000000       25
1           2      Bob   NaN  60000.0    Finance   60000.000000       29
2           3  Charlie  30.0      NaN        NaN   53571.428571       30
3           4      NaN  22.0  45000.0         IT   45000.000000       22
4           5      Eve   NaN  52000.0         HR   52000.000000       29
5           6    Frank  29.0      NaN    Finance   53571.428571       29
6           7      NaN  35.0  58000.0         IT   58000.000000       35
7           8   Hannah   NaN  61000.0        NaN   61000.000000       29
8           9      Ian  40.0      NaN    Finance   53571.428571       40
9          10     Jack  28.0  49000.0         HR   49000.000000       28

In [16]:
df['Age_function']=df['Age'].apply(lambda x:x*2)
df

,College Id,Name,Age,Salary,Department,Salary_fillNA,Age_new,Age_function
0,1,Alice,25.0,50000.0,HR,50000.000000,25,50.0
1,2,Bob,NaN,60000.0,Finance,60000.000000,29,NaN
2,3,Charlie,30.0,NaN,NaN,53571.428571,30,60.0
3,4,NaN,22.0,45000.0,IT,45000.000000,22,44.0
4,5,Eve,NaN,52000.0,HR,52000.000000,29,NaN
5,6,Frank,29.0,NaN,Finance,53571.428571,29,58.0
6,7,NaN,35.0,58000.0,IT,58000.000000,35,70.0
7,8,Hannah,NaN,61000.0,NaN,61000.000000,29,NaN
8,9,Ian,40.0,NaN,Finance,53571.428571,40,80.0
9,10,Jack,28.0,49000.0,HR,49000.000000,28,56.0

In [17]:
## Data aggregating and grouping
df

,College Id,Name,Age,Salary,Department,Salary_fillNA,Age_new,Age_function
0,1,Alice,25.0,50000.0,HR,50000.000000,25,50.0
1,2,Bob,NaN,60000.0,Finance,60000.000000,29,NaN
2,3,Charlie,30.0,NaN,NaN,53571.428571,30,60.0
3,4,NaN,22.0,45000.0,IT,45000.000000,22,44.0
4,5,Eve,NaN,52000.0,HR,52000.000000,29,NaN
5,6,Frank,29.0,NaN,Finance,53571.428571,29,58.0
6,7,NaN,35.0,58000.0,IT,58000.000000,35,70.0
7,8,Hannah,NaN,61000.0,NaN,61000.000000,29,NaN
8,9,Ian,40.0,NaN,Finance,53571.428571,40,80.0
9,10,Jack,28.0,49000.0,HR,49000.000000,28,56.0

In [18]:
grouped_mean=df.groupby('Name')['Salary_fillNA'].mean()
print(grouped_mean)

Name
Alice      50000.000000
Bob        60000.000000
Charlie    53571.428571
Eve        52000.000000
Frank      53571.428571
Hannah     61000.000000
Ian        53571.428571
Jack       49000.000000
Name: Salary_fillNA, dtype: float64

In [3]:
## Merging and joining Dataframes
# Create sample DataFrames
df1=pd.DataFrame({'Key':['A','B','C'], 'Value1':[1,2,3]})
df2=pd.DataFrame({'Key':['A','B','D'], 'Value2':[4,5,6]})
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [4]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [5]:
## Merge Dataframe 
pd.merge(df1,df2,on="Key",how="inner")  # inner, outer, left, right

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [6]:
pd.merge(df1, df2, on="Key", how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [7]:
pd.merge(df1, df2, on="Key", how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6