### Pandas-DataFrame and Series

Pandas is a powerful data manipulatioon library in python ,widely used for data analusis and data cleaning. It provides two primary data structures: Series and DataFrame. A series is a one-Dimensional array like object.

In [1]:
import pandas as pd

In [4]:
## Series is a one dimensional series.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series\n ", series)

Series
  0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
## Create a series from dictionary
data={'a':1,'b':2,'c':3,'d':4,'e':5}
series_dictionary=pd.Series(data)
print("Series from dictionary\n ", series_dictionary)

Series from dictionary
  a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
data = [10,20,30]
index = ['a','b','c']
series_with_index = pd.Series(data,index=index)
print("Series with custom index\n ", series_with_index)

Series with custom index
  a    10
b    20
c    30
dtype: int64

In [2]:
## Dataframe
## create a dataframe from dictionary of list
data={
    'Name' :['Krish','John','Jack'],
    'Age' :[25,26,24],
    'City' :['New York','Los Angeles','Chicago']
}

df=pd.DataFrame(data)
print(df)

    Name  Age         City
0  Krish   25     New York
1   John   26  Los Angeles
2   Jack   24      Chicago

In [13]:
import numpy as np
np.array(df)

array([['Krish', 25, 'New York'],
       ['John', 26, 'Los Angeles'],
       ['Jack', 24, 'Chicago']], dtype=object)

In [7]:
# create a dataframe from list of dictionary
data=[
    {'Name':'Krish','Age':25,'City':'New York'},
    {'Name':'John','Age':26,'City':'Los Angeles'},
    {'Name':'Jack','Age':24,'City':'Chicago'}
]
df1=pd.DataFrame(data)
print(df1)

    Name  Age         City
0  Krish   25     New York
1   John   26  Los Angeles
2   Jack   24      Chicago

In [29]:
df=pd.read_csv('insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [15]:
df1

    Name  Age         City
0  Krish   25     New York
1   John   26  Los Angeles
2   Jack   24      Chicago

In [9]:
df1['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: object

In [10]:
df['region']

0       southwest
1       southeast
2       southeast
3       northwest
4       northwest
          ...
1333    northwest
1334    northeast
1335    southeast
1336    southwest
1337    northwest
Name: region, Length: 1338, dtype: object

In [11]:
df1.loc[0]

Name       Krish
Age           25
City    New York
Name: 0, dtype: object

In [13]:
df1.iloc[0][0]

/var/folders/_p/8j2tcpc50y19z8pvrfpy1l840000gn/T/ipykernel_15295/1026431844.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df1.iloc[0][0]

'Krish'

In [17]:
## Accessing specified element
df1.at[1,'Name']

'John'

In [18]:
## Accesing specified element using iat
df1.iat[1,0]

'John'

In [19]:
df1

    Name  Age         City
0  Krish   25     New York
1   John   26  Los Angeles
2   Jack   24      Chicago

In [24]:
# Data manipulation
df1['Salary']=[5000,6000,7000]
df1

    Name  Age         City  Salary
0  Krish   25     New York    5000
1   John   26  Los Angeles    6000
2   Jack   24      Chicago    7000

In [ ]:
## Remove a column
df1.drop('Salary',axis=1,inplace=True)   ## axis=1 (columns) by default axis=0
df1

    Name  Age         City
0  Krish   25     New York
1   John   26  Los Angeles
2   Jack   24      Chicago

In [ ]:
df1.drop(1,axis=0,inplace=True)    ## axis=0 (rows)
df1

    Name  Age      City
0  Krish   25  New York
2   Jack   24   Chicago

In [27]:
df1

    Name  Age      City
0  Krish   25  New York
2   Jack   24   Chicago

In [33]:

df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010